### ISSUE TITLE
Issues directly editing PhatLoots YML files.

### ISSUE THREAD

**Issue by Thomoski** [Codisimus/PhatLoots#85]
Hi,
So I recently installed PhatLoot to my server, but wanted to make bulk changes to a Loot. So instead of the UI or typing commands for each item added, so I edited the YML file after adding the items in-game. I changed the amounts, probabilities and names of the collections. Before this, the file worked fine, but after editing, the Plugin now wont read the file at all. I've checked it as much as I can, and as far as I can tell there aren't any typos or errors in formatting. Any help with why the file isn't read?

https://ufile.io/7n3vw

**Comment by RiCkYB-667** [comment]
Hi!
The problem is here:

```
      - ==: Item
        ItemStack:
        BonusAmount: 10
          ==: org.bukkit.inventory.ItemStack
```

The BonusAmount line should go before or after the ItemStack setting, and not inside.

Example:

```
      - ==: Item
        ItemStack:
          ==: org.bukkit.inventory.ItemStack
          type: IRON_INGOT
          amount: 1
          meta:
            ==: ItemMeta
            meta-type: UNSPECIFIC
            lore:
            - §2Uncommon Loot
        BonusAmount: 10
        Probability: 5.0
```

Change this with every item and check if it works
